<h2 class="sb-title"><span>Mes evenements</span></h2>
<div class="sb-block">
    <div class="event-caption cfix">

        <a href="#" class="rd user-avatar bgr-darkblue"><img src="<?php echo $conf["url"]; ?>images/clip-face1.jpg" alt="" width="32" /></a>
        <strong><em>Nuit de films,</em></strong>
        <br />
        <small>venderdi 12 Decembre</small>
    </div> <!-- .cfix -->
    <p>Cet evenement est l'occasion de xxxx x x xxx xxxx xxx x x x xxxxxxxxx x x xx !</p>
    <p>
        <br />
        <strong class="blue">A venir</strong>
    </p>
    <ul class="events-list">
        <li>
            <strong><em>Nuit de films,</em></strong>
            <br />
            <small>venderdi 12 Decembre</small>
        </li>
        <li>
            <strong><em>First fraday,</em></strong>
            <br />
            <small>lundi 15 Decembre</small>
        </li>
    </ul>
</div> <!-- .sb-block -->