<h2 class="sb-title"><span>Evenements Conseilles</span></h2>
<div class="sb-block">
    <div class="event-caption cfix">
        <img width="155px" src="http://localhost/meetoparty/Dossiermembre/ff53e449/2ba2e609461fab2a0a2ff6712af675ee.jpg" />
        <br />
        <strong><em>Nuit de films,</em></strong>
        <br />
        <small>venderdi 12 Decembre</small>
    </div> <!-- .cfix -->
    <p>Cet evenement est l'occasion de xxxx x x xxx xxxx xxx x x x xxxxxxxxx x x xx !</p>
</div> <!-- .sb-block -->