<div class="blue-box-top blue-box-asdf"></div>
<div class="blue-box">
    <div class="blue-box-in cfix equal-heights">
        <div class="blue-box-col ld">
            <div class="equal">
                <p>&laquo;&nbsp;Sam, celui qui conduit, c'est celui qui ne bois pas.&nbsp;&raquo;</p>
                <p class="ra"><strong><em class="grey">Mister Cocktail</em></strong></p>            </div> <!-- .equal -->
        </div> <!-- .blue-box-col -->
        <div class="blue-box-col rd">
            <div class="equal">
                <p>&laquo;&nbsp;Ne soyez pas timide, les autres ne vont pas vous manger.&nbsp;&raquo;</p>
                <p class="ra"><strong><em class="grey">Mister Cocktail</em></strong></p>
            </div> <!-- .equal -->
        </div> <!-- .blue-box-col -->
    </div> <!-- .blue-box-in -->
</div> <!-- .blue-box -->