<div id="sidebar-left-in">
    <h2 class="sb-title"><span>Amis en linge</span></h2>
    <div class="cfix">
        <div class="sb-block">
            <ul class="users-list2 cfix">
                <li class="user">
                    <a href="#" class="user-photo bgr-pink"><img src="/Images/clip-face1.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
                <li class="user">
                    <a href="#" class="user-photo bgr-pink"><img src="/Images/clip-face2.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
                <li class="user">
                    <a href="#" class="user-photo bgr-blue"><img src="/Images/clip-face3.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
                <li class="user">
                    <a href="#" class="user-photo bgr-pink"><img src="/Images/clip-face1.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
                <li class="user">
                    <a href="#" class="user-photo bgr-blue"><img src="/Images/clip-face2.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
                <li class="user">
                    <a href="#" class="user-photo bgr-pink"><img src="/Images/clip-face3.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
                <li class="user">
                    <a href="#" class="user-photo bgr-blue"><img src="/Images/clip-face1.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
                <li class="user">
                    <a href="#" class="user-photo bgr-pink"><img src="/Images/clip-face2.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
                <li class="user">
                    <a href="#" class="user-photo bgr-pink"><img src="/Images/clip-face3.jpg" alt="" width="42" /></a>
                    <div class="user-popup-info">
                        <strong><em>Marie Nguyen,</em></strong>
                        <br /><br />
                        Ne le 24/06/1991
                        <br />
                        Etudiante a l'Universite xxx Habite a Tours
                        <div class="black-tip"></div>
                    </div>
                </li>
            </ul> <!-- .users-list2 -->
            <p class="nom">
                <br />
                <a href="#" class="rev blue">Liste d'amis</a>
            </p>
        </div>
    </div>
</div>