<meta charset="utf-8" />
<title><?php echo $conf["title"]; ?></title>
<meta name="description" content="" />
<meta name="keywords" content="" />

<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/main.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/nivo.css" media="screen" />
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>js/fancybox/jquery.fancybox.css" media="screen" />
<!--[if IE]>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>scripts/html5shiv.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>styles/ie.css" media="screen" />
<![endif]-->

<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/fancybox/jquery.fancybox.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/jquery.equalheights.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/slider.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/bind.js"></script>