        <div id="home-icons">
            <img src="<?php echo $conf["url"]; ?>Images/icon-1.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-2.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-3.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-4.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-5.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-6.png" alt="" />
        </div> <!-- #home-icons -->