                    <div class="cfix">
                        <div class="br-photo">
                            <a href="#" class="br-link bgr-pink"><img src="<?php 
                            echo $user->photoURL('1'); 
                            ?>" alt="" /></a>
                        </div> <!-- .br-photo -->
                        <div class="br-text">
                            <div><strong><em>Megane BLANC,</em></strong> vous a ecrit</div>
                            <div class="black-quote">
                                ...jeudi c'est bon pour toi ??
                                <br />
                                Je peux passer te chercher...
                                <div class="black-tip"></div>
                                <div class="funny-quotes"></div>
                            </div> <!-- .black-quote -->
                        </div> <!-- .br-text -->
                       
                        
                    </div> <!-- .cfix -->
                    <div class="br-pagination cfix">
                        <div class="pages-lbl ld">Actualites</div>
                        <ul class="pages rd">
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                        </ul>
                    </div> <!-- .br-pagination -->