<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/jquery.listederoulante.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/jquery.autocomplete.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>js/popup/style-popup.css" />

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>


<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.resize.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery-ui-1.8.8.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.autocomplete.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.text-shadow.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.border.js"></script>

<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.listederoulante.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/popup/popup.js"></script>

<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.resize.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery-ui-1.8.8.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.border.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.upload.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/popup/popup.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/changement/photoProfil.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/changement/seePassion.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/contact/ajouterContact.js"></script>

