<div class="details">
    <strong>Passions</strong><br/><br/>
    <script type="text/javascript">
        $(document).ready(function() {

            $(".category").click(function() {

                var id = this.id;
                console.log(this);
                
                $.ajax({
                    type: 'POST',
                    url: 'ajax/refreshPassion',
                    data: "idcategory=" + id,
                    dataType: 'json',
                    success:
                            function(passion) {
                                alert(passion);
                            }
                });


            });
        });
    </script>

    <p><span id="0" class="blue category">Toutes les catégories /</span>
        <?php
        $i = 1;

        while (!empty($data[$i]["id_category"])) {

            $category = ucfirst($data[$i]["name_category"]);
            ?>
            <span id="<?php echo $data[$i]["id_category"]; ?>" class="category"><?php echo $category; ?> / </span>
            <?php
            $i++;
        }
        ?>
    </p>
</div>
<br>

<div class="scroll-content-all">
    <div class="connexion-shadow-1"></div>
    <div class="scroll-pane">
        <div id="scroll-content">
            <?php
            $j = 0;

            if (empty($data["datamember"][$j]["id_category"])) {
                $errorEmptyPassion = "Aucune passion enregistrée";
            }

            if (!empty($errorEmptyPassion)) {
                echo $errorEmptyPassion;
            } else {
                while (!empty($data["datamember"][$j]["id_category"])) {

                    $category = ucfirst($data["datamember"][$j]["name_category"]);
                    $passion = ucfirst($data["datamember"][$j]["name_passion"]);

                    if (!empty($data["datamember"][$j]["icone"])) {
                        $icone = $data["datamember"][$j]["icone"];
                    } else {
                        $icone = "Images/popup-close.png";
                    }
                    ?>
                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $icone ?>" alt="" width="50"></a>
                        <span>
                            <strong><?php echo $category ?></strong><br>
                            <?php echo $passion; ?>
                        </span>
                    </div>
                    <?php
                    $j++;
                }
            }
            ?>
        </div>
    </div>
    <div class="connexion-shadow-2"></div>
</div>