<div class="details">
    <strong>Passions</strong><br/><br/>
    
    <?php 
        echo $data;
        //print_r($data);
    ?>

    Tourisme / Sport / <span class="blue">Musique</span> / Cinéma / Cuisine / Xxxxx / Xxxxx / Xxxxx / Xxxxx / Xxxxx
    Xxxxx / Xxxxx / Xxxxx / Xxxxx / Xxxxx.

</div>
<br>

<div class="scroll-content-all">
    <div class="connexion-shadow-1"></div>
    <div class="scroll-pane">
        <div id="scroll-content">

            <div class="details-user-box">
                <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                <span>
                    <strong>Stupeflip</strong><br>
                    Album xxxxxxx
                </span>
            </div>

            <div class="details-user-box">
                <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                <span>
                    <strong>Stupeflip</strong><br>
                    Album xxxxxxx
                </span>
            </div>

            <div class="details-user-box">
                <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                <span>
                    <strong>Stupeflip</strong><br>
                    Album xxxxxxx
                </span>
            </div>
            <div class="details-user-box">
                <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                <span>
                    <strong>Stupeflip</strong><br>
                    Album xxxxxxx
                </span>
            </div>
            <div class="details-user-box">
                <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                <span>
                    <strong>Stupeflip</strong><br>
                    Album xxxxxxx
                </span>
            </div>
        </div>
    </div>
    <div class="connexion-shadow-2"></div>
</div>