<div id="home-slider" class="slider-container">
        <div class="slider-container-in">
          <div class="slider">
            <img src="<?php echo $conf["url"]; ?>Images/slider-1.jpg" alt="" title="- Vous aimez faire la fête ? -" />
            <img src="<?php echo $conf["url"]; ?>Images/slider-2.jpg" alt="" title="- Vous aimez faire des rencontres ? -" />
            <img src="<?php echo $conf["url"]; ?>Images/slider-3.jpg" alt="" title="- Vous aimez sortir ? -" />
          </div> <!-- .slider -->
        </div> <!-- .slider-container-in -->
      </div> <!-- #home-slider -->

      <div id="home-icons">
        <img src="<?php echo $conf["url"]; ?>Images/icon-1.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-2.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-3.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-4.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-5.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-6.png" alt="" />
      </div> <!-- #home-icons -->

      <div class="blue-box-top"></div>
      <div class="blue-box">
        <div class="blue-box-in cfix equal-heights">
          <div class="blue-box-col ld">
            <div class="equal">
              <h2>Qu’est ce que Meetoparty ?</h2>
              <p>Origine de vos futurs évènements, ce site est le cocktail parfait entre réseau social et site de rencontres. Cette révolution dont vous connaissez déjà le principe, s’offre à vous comme étant un outil gratuit et simple d’utilisation. Meetoparty est le résultat final d’une étude sur l’évolution des relations sociales. Aujourd’hui, peu sont ceux qui osent aller vers une personne inconnue. Meetoparty a pour objectif de changer le cours des choses.</p>
              <p>Meetoparty vous propose un moyen ludique et attractif d’organiser des rencontres réelles avec des inconnus dans le cadre du partage de vos passions. A la clé ? Se créer de nouveaux liens d’amitié et plus si affinités.</p>
            </div> <!-- .equal -->
          </div> <!-- .blue-box-col -->
          <div class="blue-box-col rd">
            <div class="equal">
              <h2>Faites des rencontres qui vous ressemblent !</h2>
              <p>Marre des soirées ou des sorties où vous ne vous sentez pas à votre place ? Envie de nouvelles expériences ou de faire de nouvelles connaissances ? Meetoparty est fait pour vous !</p>
              <p>Meetoparty vous accompagne et vous aide dans votre démarche en vous permettant de créer des centaines d’évènements, sorties ou soirées possibles en lien avec vos passions !</p>
              <p>Déclencheur de rencontres, nous vous souhaitons de merveilleux moments.</p>
            </div> <!-- .equal -->
          </div> <!-- .blue-box-col -->
        </div> <!-- .blue-box-in -->
      </div> <!-- .blue-box -->