<h2 class="sb-title"><span>Recapitulatif</span></h2>
<div class="cfix">
    <div class="sb-block">
        0 nouveaux messages
        <br />
        <strong>5 visites</strong> <a href="#" class="rev blue"> Voir statistiques</a>
        <br />
        <strong>5 evenements</strong> en cours
        <br />
        <strong>15 contacts</strong>
        <br />
        <strong>26 begins</strong> sur vous
        <br />
        <strong>40 photos</strong> de vos activites
    </div> <!-- .sb-block -->
</div> <!-- .cfix -->