<?php
if ($user->sex_member == 1) {
    $born = "Né";
} else {
    $born = "Née";
}
?>
<div class="bl-photo">
    <strong><em><?php echo $user->pseudo_member; ?></em></strong>
    <br /><br />
    <a href="/profil/id/<?php echo $user->id_member; ?>" class="bl-link bgr-blue"><img id="avatar-profil" width="101px" src="<?php echo $user->photoURL(); ?>" alt="" /></a>
</div> <!-- .bl-photo -->
<div class="bl-right">
    <div>
        <?php
        $birth = $user->birth_member;
        $year = $user->Yeardate($birth);
        $m = $user->Monthdate($birth);
        $day = $user->Daydate($birth);
        $month = $user->month($m);

        $age = $user->Age($birth);
        ?>
        <?php echo $user->city_member; ?>
        <br />
        <?php echo $age; ?> Ans
    </div>
    <div class="white-quote">
        <div class="white-tip"></div>
        Partager vos idées ! 
        <a href="#" class="btn-partager rep">Partager</a>
    </div> <!-- .white-quote -->
</div> <!-- .bl-right -->