<div id="connexion-bar"></div>
<div id="connexion-box">
    <div id="connexion-box-in">
        <h3 class="cbox-title blue">Bienvenue !</h3>
        <div class="connexion-shadow-1"></div>
        <p>Page d'actualité</p>

        <div class="connexion-shadow-2"></div>
        <?php if (isset($contr)) $contr->loadvWidget("mosaic_pictures"); ?>
    </div> <!-- #connexion-box-in -->
</div> <!-- #connexion-box -->

<?php if (isset($contr)) $contr->loadvWidget("footer_quotation"); ?>

<div style="display:none;"></div>
