
<div id="inside-main" class="cfix">
    <div id="sidebar-left">
        <div id="sidebar-left-in">
            <?php if (isset($contr)) $contr->loadvWidget("friends_online"); ?>
        </div> <!-- #sidebar-left-in -->
    </div> <!-- #sidebar-left -->

    <div id="sidebar-right">
        <div id="sidebar-right-in">
            <?php if (isset($contr)) $contr->loadvWidget("events_my"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("events_sugest"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("sponsoring"); ?>
        </div> <!-- #sidebar-right-in -->
    </div> <!-- #sidebar-right -->

    <!-- This is the main content area -->
    <div id="inside-column">
        <hr class="top-bar"/>
        <?php //include 'Modules/tchat/notifications.php';  ?>
        <span class="title_event_header"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-fav.png" alt="" class="vam blue-man" width="27" />Actualités</span>
        <hr class="clear"/>
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="cfix">
                <div class="conversation-main">
                    <div class="conversation-main-inside">
                        <div class="chat-meta"><strong><em>Thomas MARTIN</em></strong></div>
                        <div class="chat-msg bgr-blue">
                            Coucou Lea!
                            <div class="chat-tip-left"></div>
                        </div> <!-- .chat-msg -->
                        <div class="chat-meta"><a href="#" class="rev blue">
                                <span class="vam">Voir l'evenement</span>
                                <img src="images/icon-dude.png" alt="" class="vam" />
                            </a></div>
                    </div> <!-- .conversation-main-inside -->
                </div> <!-- .conversation-main -->

                <div class="conversation-left">
                    <a href="#" class="user-avatar bgr-blue"><img src="images/clip-face2.jpg" alt="" width="42" /></a>
                </div> <!-- .conversation-left -->
            </div> <!-- .cfix -->
        </div> <!-- .inside-column-inside -->
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="cfix">
                <div class="conversation-main">
                    <div class="conversation-main-inside">
                        <div class="chat-meta ra"><strong><em>Thomas MARTIN</em></strong></div>
                        <div class="chat-msg bgr-pink2">
                            Coucou Lea!
                            <div class="chat-tip-right"></div>
                        </div> <!-- .chat-msg -->
                        <div class="chat-meta"><a href="#" class="rev blue">
                                <span class="vam">Voir l'evenement</span>
                                <img src="images/icon-heart.png" alt="" class="vam" />
                            </a></div>
                    </div> <!-- .conversation-main-inside -->
                </div> <!-- .conversation-main -->
                <div class="conversation-right">
                    <a href="#" class="user-avatar bgr-pink"><img src="images/clip-face1.jpg" alt="" width="42" /></a>
                </div> <!-- .conversation-left -->
            </div> <!-- .cfix -->
        </div> <!-- .inside-column-inside -->
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="cfix">
                <div class="conversation-main">
                    <div class="conversation-main-inside">
                        <div class="chat-meta ra"><strong><em>Thomas MARTIN</em></strong></div>
                        <div class="chat-msg bgr-pink2">
                            Coucou Lea!
                            <div class="chat-tip-left"></div>
                        </div> <!-- .chat-msg -->
                        <div class="chat-meta"><a href="#" class="rev blue">
                                <span class="vam">Voir l'evenement</span>
                                <img src="images/icon-games.png" alt="" class="vam" />
                            </a></div>
                    </div> <!-- .conversation-main-inside -->
                </div> <!-- .conversation-main -->
                <div class="conversation-left">
                    <a href="#" class="user-avatar bgr-pink"><img src="images/clip-face1.jpg" alt="" width="42" /></a>
                </div>
            </div> <!-- .cfix -->
        </div> <!-- .inside-column-inside -->
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="cfix">
                <div class="conversation-main">
                    <div class="conversation-main-inside">
                        <div class="chat-meta ra"><strong><em>Thomas MARTIN</em></strong></div>
                        <div class="chat-meta">
                            Manon LALO a partage des photos de l'evenement XXXXXX
                        </div>
                        <div class="chat-meta"><a href="#" class="rev blue">
                                <span class="vam">Voir l'evenement</span>
                                <img src="images/icon-heart.png" alt="" class="vam" />
                            </a></div>
                        <div class="photos-box">
                            <div class="cfix">
                                <a href="#" class="ld"><img src="images/clip-photos.jpg" alt="" /></a>
                                <div class="photos-box-text blue">
                                    36 photos
                                    <br /><br /><br /><br /><br />
                                    <img src="images/icon-dude.png" alt="" />
                                    <strong>Decouvrir l'album...</strong>
                                </div> <!-- .photos-box-text -->
                            </div> <!-- .cfix-->
                        </div> <!-- .photos-box -->
                    </div> <!-- .conversation-main-inside -->
                </div> <!-- .conversation-main -->
                <div class="conversation-right">
                    <a href="#" class="user-avatar bgr-pink"><img src="images/clip-face1.jpg" alt="" width="42" /></a>
                </div> <!-- .conversation-left -->
            </div> <!-- .cfix -->
        </div>
    </div>

</div>
</div> <!-- #inside-column -->
<div id="main-footer">
    <?php if (isset($contr)) $contr->loadvWidget("mosaic_pictures"); ?>
</div> <!-- #main-footer -->
</div> <!-- .cfix -->
<?php if (isset($contr)) $contr->loadvWidget("footer_quotation"); ?>
<div style="display:none;"></div>
