
<div id="connexion-bar"></div>
<div id="connexion-box">
    <div id="connexion-box-in">
        <h3 class="cbox-title blue"><?php echo $data["title"]; ?> </h3>
        <div class="connexion-shadow-1"></div>
        

        <?php
        echo $data['error'];
        ?>

        <div class="contentainer-div-villy amins-div">
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-inscription.png" width="179" height="179" alt="Inscription"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-connexion.png" width="179" height="179" alt="Connexion"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-profil.png" width="179" height="179" alt="Profil"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-messagerie.png" width="179" height="179" alt="Messagerie"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-evenements.png" width="179" height="179" alt="Evenements"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-passions.png" width="179" height="179" alt="Passions"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-tchat.png" width="179" height="179" alt="Tchat"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-amins.png" width="179" height="179" alt="Amins"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-contact.png" width="179" height="179" alt="Contact"></a>
            <a href="#"><img src="<?php echo $conf["url"]; ?>Images/aide-faq.png" width="179" height="179" alt="Faq"></a>
        </div>


        <div class="connexion-shadow-2"></div>
        <div id="home-icons">
            <img src="<?php echo $conf["url"]; ?>Images/icon-1.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-2.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-3.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-4.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-5.png" alt="" />
            <img src="<?php echo $conf["url"]; ?>Images/icon-6.png" alt="" />
        </div> <!-- #home-icons -->
    </div> <!-- #connexion-box-in -->
</div> <!-- #connexion-box -->

