<div id="footer">
                <ul id="footer-links">
                    <li><a href="#" class="rev">Mentions légales</a></li>
                    <li><a href="index.php?page=contact" class="rev">Contactez-nous</a></li>
                    <li><a href="#" class="rev">Publicité</a></li>
                    <li><a href="index.php?page=index-entreprise" class="rev">Entreprises</a></li>
                    <li><a href="#" class="rev">Confidentialité</a></li>
                    <li><a href="#" class="rev">Conditions d’utilisation</a></li>
                    <li><a href="#" class="rev">Aide</a></li>
                    <li><a href="#" class="rev">Meetoparty ®</a></li>
                </ul>

                <div class="cfix designed-cont">
                    <div class="designed ld">
                        <span class="designed-line ld">&nbsp;</span>
                        <span class="designed-line rd">&nbsp;</span>
                    </div> <!-- .designed -->
                    <div class="designed rd">
                        <span class="designed-line ld">&nbsp;</span>
                        <span class="designed-line rd">&nbsp;</span>
                    </div> <!-- .designed -->
                    <div id="footer-logo"></div>
                </div> <!-- .cfix -->
            </div> <!-- #footer -->
        </div> <!-- #wrap-outer -->

        <div style="display:none;">
        </div>
    </body>
</html>