<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="utf-8" />
        <title><?php echo $conf["title"];
echo $data ? " - $data" : "";
?></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/main.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/nivo.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>js/fancybox/jquery.fancybox.css" media="screen" />
        <!--[if IE]>
        <script type="text/javascript" src="<?php echo $conf["url"]; ?>scripts/html5shiv.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>styles/ie.css" media="screen" />
        <![endif]-->

        <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/jquery.js"></script>
        <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/fancybox/jquery.fancybox.js"></script>
        <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/jquery.equalheights.js"></script>
        <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/slider.js"></script>
        <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/bind.js"></script>
    </head>
    <body>
        <div id="wrap-outer">
            <div id="logo-block">
                <a href="index.php" id="logo" class="rep">MeetoParty</a>
                <div id="top-social-links">
                    <a href="http://www.facebook.com/Meetoparty" id="top-facebook-link" class="rep">Facebbok</a>
                    <a href="https://twitter.com/Meetoparty" id="top-twitter-link" class="rep">Twitter</a>
                </div> <!-- #top-social-links -->
                <div id="top-small-title">
                    Associez vos <span class="blue">envies</span>
                    <br />
                    au rythme de vos <span class="blue">hobbies!</span>
                </div> <!-- #top-small-title -->
            </div> <!-- #logo-block -->

            <div id="header" class="cfix">
                <div id="header-left">
                    <div id="header-left-in1">
                        <div id="header-left-in2">
                            <ul class="menu" id="left-menu">
                                <li><a href="#">
                                        <span class="menu-icon"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-fav.png" alt="" /></span>
                                        <span class="menu-text">Evenement</span>
                                    </a></li>
                                <li><a href="#">
                                        <span class="menu-icon"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-messages.png" alt="" /></span>
                                        <span class="menu-text">Discussion</span>
                                    </a></li>
                                <li><a href="index.php?page=listecontact">
                                        <span class="menu-icon"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-users.png" alt="" /></span>
                                        <span class="menu-text">Contact</span>
                                    </a></li>
                                <li><a href="index.php?page=voirprofil">
                                        <span class="menu-icon"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-user.png" alt="" /></span>
                                        <span class="menu-text">Profil</span>
                                    </a></li>
                                <li class="nom"><a href="index.php">
                                        <span class="menu-icon"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-home.png" alt="" /></span>
                                        <span class="menu-text">Accueil</span>
                                    </a></li>
                            </ul>
                        </div> <!-- #header-left-in2 -->
                    </div> <!-- #header-left-in1 -->
                </div> <!-- #header-left -->
                <div id="header-right">
                    <div id="header-right-in1">
                        <div id="header-right-in2">
                            <ul class="menu" id="right-menu">
                                <li><a href="index.php?page=messagerie">
                                        <span class="menu-icon"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-email.png" alt="" /></span>
                                        <span class="menu-text">Message</span>
                                    </a></li>
                                <li class="nom"><a href="#">
                                        <span class="menu-icon"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-news.png" alt="" /></span>
                                        <span class="menu-text">News</span>
                                    </a></li>
                            </ul>

                            <div id="recherche-box">
                                <div class="cfix">
                                    <a href="#" class="ld"><img src="<?php echo $conf["url"]; ?>Images/btn-recherche.png" alt="" /></a>
                                    <a href="/logout" class="rd"><img src="<?php echo $conf["url"]; ?>Images/btn-decon.png" alt="" /></a>
                                </div> <!-- .cfix -->
                                <form method="get" action="#" class="search-form">
                                    <fieldset>
                                        <input type="text" class="text" name="search" id="search" value="" />
                                        <input type="submit" class="submit" value="" title="Submit data" />
                                    </fieldset>
                                </form>
                            </div> <!-- #recherche-box -->
                        </div> <!-- #header-right-in2 -->
                    </div> <!-- #header-right-in1 -->
                </div> <!-- #header-right-->
            </div> <!-- #header -->

            <div class="beta cfix">
                <div class="beta-left">
                    <div class="bl-photo">
                        <strong><em><?php echo $user->pseudo_member; ?></em></strong>
                        <br /><br />
                        <a href="#" class="bl-link bgr-blue"><img src="<?php echo $user->photoURL(); ?>" alt="" /></a>
                    </div> <!-- .bl-photo -->
                    <div class="bl-right">
                        <div>
                            Ne le <?php echo $user->birth_member; ?>
                            <br />
                            Travail chez xxxx
                        </div>
                        <div class="white-quote">
                            <div class="white-tip"></div>
                            Partagetr vos idees...!
                            <a href="#" class="btn-partager rep">Partager</a>
                        </div> <!-- .white-quote -->
                    </div> <!-- .bl-right -->
                </div> <!-- .beta-left -->
                <div class="beta-right">
                   <?php $contr->loadvWidget("news"); ?>
                </div> <!-- .beta-right -->
            </div> <!-- .beta -->