
<script type="text/javascript">var iddumembre=<?php echo $data->id_member;?>;</script>
<?php if (isset($contr)) $contr->loadvWidget("profil_js_include"); ?>

<div class="popup-other popup-othermini" style="display: none; "></div>

<div id="inside-main" class="cfix">
    <div id="sidebar-left">
        <div id="sidebar-left-in">
            <?php
            //include 'Modules/amis/listeamis.php';
            ?>
            <?php
            /*             * ************************************************* TCHAT *************************************** */
            //include 'Modules/tchat/tchat-left.php';
            /*             * ************************************************* FINTCHAT *************************************** */
            ?>

            <?php if (isset($contr)) $contr->loadvWidget("statistics"); ?>
        </div> <!-- #sidebar-left-in -->
    </div> <!-- #sidebar-left -->

    <div id="sidebar-right">
        <div id="sidebar-right-in">
            <?php if (isset($contr)) $contr->loadvWidget("events_my"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("events_sugest"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("sponsoring"); ?>
        </div> <!-- #sidebar-right-in -->
    </div> <!-- #sidebar-right -->

    <!-- This is the main content area -->
    <div id="inside-column">
        <hr class="top-bar"/>
        <?php //include 'Modules/tchat/notifications.php'; ?>
        <span class="title_event_header"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-fav.png" alt="" class="vam blue-man" width="27" />Mon profil</span>
        <hr class="clear"/>
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="cfix">
                <div class="conversation-main">
                    <div class="conversation-main-inside cfix">
                        <div class="ld user-titlro">
                            <div id="addcontact"><?php if($data->addcontact != "") echo $data->addcontact;?></div>
                            <strong><em><?php echo $data->error? $data->error: ucfirst($data->pseudo_member); ?></em></strong>
                            <br /><br />
                            <strong><em><a href="#" class="rev blue">Profil</a></em></strong>
                        </div> <!-- .user-titlro -->
                        <ul class="user-iconies cfix">
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-resume.png" alt="" /></span>
                                    <span class="user-iconies-2">Profil</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-photos.png" alt="" /></span>
                                    <span class="user-iconies-2">Photos</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-passions.png" alt="" /></span>
                                    <span class="user-iconies-2">Passions</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-contact.png" alt="" /></span>
                                    <span class="user-iconies-2">Contacts</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-parameter.png" alt="" /></span>
                                    <span class="user-iconies-2">Paramètres</span>
                                </a></li>
                        </ul> <!-- .user-iconies -->
                    </div> <!-- .conversation-main-inside -->
                </div>
                <div class="conversation-left">
                    <a href="#" class="user-avatar bgr-blue"><img src="/<?php echo $data->photo_member; ?>" alt="" width="42" /></a>
                    <a href="javascript:void()" id="modifAvatar">Modifier ma photo</a>
                </div> <!-- .conversation-left -->
            </div> <!-- .cfix -->
        </div>
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="big-main">
                <strong><em>Informations generales</em></strong>
                <br /><br />
                <p>Pseudo : <?php echo isset($data->pseudo_member)?$data->pseudo_member:""; ?></p>
                Age : 
                <br />
                Date d'anniversaire :
                <br />
                Sexe :
                <br /><br />
                <strong><em>Details</em></strong>
                <br /><br />
                Prenom : 
                <br />
                Ville : 
                <br />
                Pays : 
                <br />
                Situation : 
                <br />
                Interesse par :
                <br />
                Etudes :
                <br /><br />
                <strong><em>A propos de vous</em></strong>
                <br /><br />
                <strong><em>Informations supplementaries</em></strong>
                <br /><br />
                Adresse msn :
                <br />
                Pseudo skype : <?php echo isset($data->skype_member)?$data->skype_member:""; ?>
                <br />
                Lien facebook :
            </div> <!-- .big-main -->
        </div>
    </div>
</div> <!-- #inside-column -->
<div id="main-footer">
    <div class="connexion-shadow-2 nom"></div>
    <?php if (isset($contr)) $contr->loadvWidget("mosaic_pictures"); ?>
</div> <!-- #main-footer -->
</div> <!-- .cfix -->
<?php if (isset($contr)) $contr->loadvWidget("footer_quotation"); ?>
<div style="display:none;"></div>
