<?php
if ($data->id_member != $_SESSION['id_member']) {
    $own = false;
} else {
    $own = true;
}

if ($own == true) {
    ?>
    <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jeditable.js"></script>
    <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/profil/modify-profil.js"></script>
    <?php
}
?>

<div class="popup-other popup-othermini" style="display: none; "></div>
<!-- the jScroll script -->
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/scroll.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.scroll-pane').jScrollPane({
            verticalDragMaxHeight: 42
        });

    });
</script>

<script type="text/javascript">
    $(document).ready(function() {
        $('.scroll-pane').jScrollPane({
            verticalDragMaxHeight: 42
        });

    });
</script>
<div id="inside-main" class="cfix">
    <div id="sidebar-left">
        <div id="sidebar-left-in">
            <?php
            //include 'Modules/amis/listeamis.php';
            ?>
            <?php
            /*             * ************************************************* TCHAT *************************************** */
            //include 'Modules/tchat/tchat-left.php';
            /*             * ************************************************* FINTCHAT *************************************** */
            ?>

            <?php if (isset($contr)) $contr->loadvWidget("statistics"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("friends_online"); ?>
        </div> <!-- #sidebar-left-in -->
    </div> <!-- #sidebar-left -->

    <div id="sidebar-right">
        <div id="sidebar-right-in">
            <?php if (isset($contr)) $contr->loadvWidget("events_my"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("events_sugest"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("sponsoring"); ?>
        </div> <!-- #sidebar-right-in -->
    </div> <!-- #sidebar-right -->

    <!-- This is the main content area -->
    <div id="inside-column">
        <hr class="top-bar"/>
        <?php //include 'Modules/tchat/notifications.php';   ?>
        <?php
        if ($own == true) {
            $message_profil = "Mon profil";
        } else {
            $message_profil = "Profil de $data->pseudo_member";
        }
        ?>
        <span class="title_event_header"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-fav.png" alt="" class="vam blue-man" width="27" /><?php echo $message_profil; ?></span>
        <hr class="clear"/>
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="cfix">
                <div class="conversation-left">
                    <a href="#" class="user-avatar bgr-blue"><img src="/<?php echo $data->error ? $data->error : $data->photo_member; ?>" alt="" width="42" /></a>
                    <a href="javascript:void()" id="modifAvatar">Modifier ma photo</a>
                </div> <!-- .conversation-left -->
                <div class="conversation-main">
                    <div class="conversation-main-inside cfix">
                        <div class="ld user-titlro">
                            <strong><em><?php echo $data->error ? $data->error : ucfirst($data->pseudo_member); ?></em></strong>
                            <strong><em><a href="#" class="rev blue">Profil</a></em></strong>
                        </div> <!-- .user-titlro -->
                        <ul class="user-iconies cfix">
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-actuality.png" alt="" /></span>
                                    <span class="user-iconies-2">Actualités</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-photos.png" alt="" /></span>
                                    <span class="user-iconies-2">Photos</span>
                                </a></li>
                            <li><a href="/profil/id/<?php echo $data->id_member; ?>">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-details.png" alt="" /></span>
                                    <span class="user-iconies-2">Détails</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-event.png" alt="" /></span>
                                    <span class="user-iconies-2">Evènements</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-contacts.png" alt="" /></span>
                                    <span class="user-iconies-2">Contacts</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-parameter.png" alt="" /></span>
                                    <span class="user-iconies-2">Paramètres</span>
                                </a></li>
                        </ul> <!-- .user-iconies -->
                    </div> <!-- .conversation-main-inside -->
                </div>
            </div> <!-- .cfix -->
        </div>
        <div class="inside-column-sep"></div>
        <ul id="details-menu">
            <li><img style="opacity:0.7;" src="<?php echo $conf["url"]; ?>Images/details_glass.png" alt="Photos"/></li>
            <li><h4 class="details-main-title">Détails</h4></li>
            <li><div id="addcontact"><?php if ($data->addcontact != "") echo $data->addcontact; ?></div></li>
            <?php
            if ($own == false) {
                ?>
                <li><a href="#" class="details-btn">Ecrire un message</a></li>
                <li><a href="#" class="details-btn2">Tchater</a></li>
                <?php
            }
            ?>
        </ul>
        <?php
        if ($data->sex_member == HOMME) {
            $sexe = "Homme";
        } else {
            $sexe = "Femme";
        }
        ?>
        <div class="details">
            <div id="map">
                <?php
                // MAP and region detection with a function in the user library
                $idregion = $data->CodeRegionId($data->zipcode_member);
                ?>
                <img id="details-map" src="<?php echo $conf["url"]; ?>Images/region-map/<?php echo $idregion; ?>.png" width="360" height="380" alt="Map">
            </div>
            <h3 class="details-title">Informations générales</h3>
            <p><strong>Pseudo</strong> : <span id="pseudo"><?php echo $data->error ? $data->error : ucfirst($data->pseudo_member); ?></span></p>
            <span class="form-validation-pseudo" style="color:red;"></span>
            <strong>Age</strong> : <?php echo $data->Age($data->birth_member); ?> ans<br/>
            <?php
            // For the month of birth
            $mon = $data->Monthdate($data->birth_member);
            $month = $data->month($mon);
            ?>
            <strong>Anniversaire</strong> : Le <?php
            echo $data->Daydate($data->birth_member);
            echo " $month";
            ?><br/>
            <p><strong>Sexe</strong><span id="sexe"> : <?php echo $sexe; ?></span></p>

            <strong>Ville</strong> : <?php echo ucfirst(strtolower($data->city_member)); ?><br/>
            <strong>Pays</strong> : <?php echo $data->country_member; ?><br/>
            <?php
            $day2 = $data->Daydate($data->inscription_date_member);
            $mon2 = $data->Monthdate($data->inscription_date_member);
            $month2 = $data->month($mon2);
            $year2 = $data->Yeardate($data->inscription_date_member);
            ?>
            <strong>Date d'inscription</strong> : <?php echo "Le $day2 $month2 $year2" ?><br/>
            <br/>

            <h3 class="details-title">Détails</h3>
            <?php
            if ($data->statut_member == NULL) {
                $data->statut_member = NCE;
            } else if ($data->statut_member == 1) {
                $data->statut_member = SINGLE;
            } else if ($data->statut_member == 2) {
                $data->statut_member = COUPLE;
            } else if ($data->statut_member == 3) {
                if ($sexe == "Femme") {
                    $data->statut_member = BRIDE;
                } else {
                    $data->statut_member = MARIED;
                }
            }

            if ($sexe == "Femme") {
                $situation_class = "2";
            } else {
                $situation_class = "1";
            }
            ?>
            <p><strong>Situation</strong> : <span id="situation<?php echo $situation_class; ?>"><?php echo $data->statut_member; ?></span></p>
            <?php
            $interest = "Intéréssé par";
            if ($sexe == "Femme") {
                $interest = "Intéressée par";
            }
            if ($data->preference_member == NULL) {
                $preference = NC;
            } else if ($data->preference_member == P_M) {
                $preference = "Homme";
            } else if ($data->preference_member == P_W) {
                $preference = "Femme";
            } else if ($data->preference_member == P_B) {
                $preference = "Homme et Femme";
            }
            ?>
            <p><strong><?php echo $interest; ?></strong> : <span id="preferance"><?php echo $preference; ?></span></p>
            <?php
            if ($data->study_member == COLLEGE) {
                $study = "Collège";
            } else if ($data->study_member == LYCEE) {
                $study = "Lycée";
            } else if ($data->study_member == BAC1) {
                $study = "BAC + 1";
            } else if ($data->study_member == BAC2) {
                $study = "BAC + 2";
            } else if ($data->study_member == BAC3) {
                $study = "BAC + 3";
            } else if ($data->study_member == BAC4) {
                $study = "BAC + 4";
            } else if ($data->study_member == BAC5) {
                $study = "BAC + 5";
            } else if ($data->study_member == BAC6) {
                $study = " > BAC + 5";
            } else if ($data->study_member == JOBLOOKING) {
                $study = "En recherche d'emploi";
            } else if ($data->study_member == EMPLOYEE) {
                $study = "Salarié";
            } else if ($data->study_member == FREELANCE) {
                $study = "Freelance";
            } else if ($data->study_member == NCE) {
                $study = "Non communiquée";
            }
            ?>
            <p><strong>Situation professionnelle</strong> : <span id="situationpro"><?php echo $study; ?></span></p>

            <br/>

            <h3 class="details-title">A propos de vous</h3>
            <?php
            if ($data->first_name_member == NULL) {
                $data->first_name_member = NC;
            }
            ?>
            <p><strong>Prénom</strong> : <span id="first-name"><?php echo $data->first_name_member; ?></span></p>
            <?php
            if ($data->skype_member == NULL) {
                $data->skype_member = NC;
            }
            ?>
            <strong>Pseudo skype</strong> : <?php echo $data->skype_member; ?><br/>
            <?php
            if ($data->facebook_member == NULL) {
                $data->facebook_member = NC;
                ?>
                <strong>Lien Facebook</strong> : <?php echo $data->facebook_member; ?><br/>
                <?php
            } else {
                ?>
                <a href="<?php echo $data->facebook_member; ?>"><img src="<?php echo $conf["url"]; ?>/Images/facebook-logo.jpg" width="10%" alt="Profil Facebook" /></a><br/>
                <?php
            }
            ?>

            <?php
            if ($data->twitter_member == NULL) {
                $data->twitter_member = NC;
                ?>
                <strong>Lien Twitter</strong> : <?php echo $data->twitter_member; ?><br/>
                <?php
            } else {
                ?>
                <a href="<?php echo $data->facebook_member; ?>"><img src="<?php echo $conf["url"]; ?>/Images/twitter-logo.jpg" width="10%" alt="Profil Facebook" /></a>
                <?php
            }
            ?>
            <?php
            if ($data->extra_email_member == NULL) {
                $data->extra_email_member = NC;
            }
            ?>
            <strong>Email</strong> : <?php echo $data->extra_email_member; ?><br/>    

            <?php
            if ($data->cellular_member == NULL) {
                $data->cellular_member = NC;
            }
            ?>
            <strong>Portable</strong> : <?php echo $data->cellular_member; ?><br/>

            <br/>
            <h3 class="details-title">Description</h3>
            <?php
            if ($data->description_member == NULL) {
                $data->description_member = NCE;
            }
            ?>
            <strong>Description du membre</strong> : <?php echo $data->description_member; ?><br/>

            <?php
            if ($data->description_research_member == NULL) {
                $data->description_research_member = NCE;
            }
            ?>
            <strong>A la recherche</strong> : <?php echo $data->description_research_member; ?><br/>
            <hr class="clear"/>
        </div>
        <div class="inside-column-sep"></div>
        <div class="details">
            <strong> Passions</strong><br>

            Tourisme / Sport / <span class="blue">Musique</span> / Cinéma / Cuisine / Xxxxx / Xxxxx / Xxxxx / Xxxxx / Xxxxx
            Xxxxx / Xxxxx / Xxxxx / Xxxxx / Xxxxx.

        </div>
        <br>

        <div class="scroll-content-all">
            <div class="connexion-shadow-1"></div>
            <div class="scroll-pane">
                <div id="scroll-content">

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                </div>
            </div>
            <div class="connexion-shadow-2"></div>
        </div>

    </div>

</div>
</div> <!-- #inside-column -->
<div id="main-footer">
    <?php if (isset($contr)) $contr->loadvWidget("mosaic_pictures"); ?>
</div> <!-- #main-footer -->
</div> <!-- .cfix -->
<?php if (isset($contr)) $contr->loadvWidget("footer_quotation"); ?>
<div style="display:none;"></div>
