<?php
if ($data->id_member != $_SESSION['id_member']) {
    $own = false;
} else {
    $own = true;
}
?>

<div class="popup-other popup-othermini" style="display: none; "></div>
<!-- the jScroll script -->
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/scroll.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.scroll-pane').jScrollPane({
            verticalDragMaxHeight: 42
        });
		
    });
</script>

<script type="text/javascript">
    $(document).ready(function() {
        $('.scroll-pane').jScrollPane({
            verticalDragMaxHeight: 42
        });
		
    });
</script>
<div id="inside-main" class="cfix">
    <div id="sidebar-left">
        <div id="sidebar-left-in">
            <?php
            //include 'Modules/amis/listeamis.php';
            ?>
            <?php
            /*             * ************************************************* TCHAT *************************************** */
            //include 'Modules/tchat/tchat-left.php';
            /*             * ************************************************* FINTCHAT *************************************** */
            ?>

            <?php if (isset($contr)) $contr->loadvWidget("statistics"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("friends_online"); ?>
        </div> <!-- #sidebar-left-in -->
    </div> <!-- #sidebar-left -->

    <div id="sidebar-right">
        <div id="sidebar-right-in">
            <?php if (isset($contr)) $contr->loadvWidget("events_my"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("events_sugest"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("sponsoring"); ?>
        </div> <!-- #sidebar-right-in -->
    </div> <!-- #sidebar-right -->

    <!-- This is the main content area -->
    <div id="inside-column">
        <hr class="top-bar"/>
        <?php //include 'Modules/tchat/notifications.php';  ?>
        <?php
        if ($own == true) {
            $message_profil = "Mon profil";
        } else {
            $message_profil = "Profil de $data->pseudo_member";
        }
        ?>
        <span class="title_event_header"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-fav.png" alt="" class="vam blue-man" width="27" /><?php echo $message_profil; ?></span>
        <hr class="clear"/>
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="cfix">
                <div class="conversation-left">
                    <a href="#" class="user-avatar bgr-blue"><img src="/<?php echo $data->error ? $data->error : $data->photo_member; ?>" alt="" width="42" /></a>
                    <a href="javascript:void()" id="modifAvatar">Modifier ma photo</a>
                </div> <!-- .conversation-left -->
                <div class="conversation-main">
                    <div class="conversation-main-inside cfix">
                        <div class="ld user-titlro">
                            <strong><em><?php echo $data->error ? $data->error : ucfirst($data->pseudo_member); ?></em></strong>
                            <strong><em><a href="#" class="rev blue">Profil</a></em></strong>
                        </div> <!-- .user-titlro -->
                        <ul class="user-iconies cfix">
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-actuality.png" alt="" /></span>
                                    <span class="user-iconies-2">Actualités</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-photos.png" alt="" /></span>
                                    <span class="user-iconies-2">Photos</span>
                                </a></li>
                            <li><a href="/profil/id/<?php echo $data->id_member; ?>">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-details.png" alt="" /></span>
                                    <span class="user-iconies-2">Détails</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-event.png" alt="" /></span>
                                    <span class="user-iconies-2">Evènements</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-contacts.png" alt="" /></span>
                                    <span class="user-iconies-2">Contacts</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-parameter.png" alt="" /></span>
                                    <span class="user-iconies-2">Paramètres</span>
                                </a></li>
                        </ul> <!-- .user-iconies -->
                    </div> <!-- .conversation-main-inside -->
                </div>
            </div> <!-- .cfix -->
        </div>
        <div class="inside-column-sep"></div>
        <ul id="details-menu">
            <li><img style="opacity:0.7;" src="<?php echo $conf["url"]; ?>Images/details_glass.png" alt="Photos"/></li>
            <li><h4>Détails</h4></li>
            <li><div id="addcontact"><?php if ($data->addcontact != "") echo $data->addcontact; ?></div></li>
            <?php
            if ($own == false) {
                ?>
                <li><a href="#" class="details-btn">Ecrire un message</a></li>
                <li><a href="#" class="details-btn2">Tchater</a></li>
                <?php
            }
            ?>
        </ul>
        <?php
        if ($data->sex_member == "1") {
            $sexe = "Homme";
        } else {
            $sexe = "Femme";
        }
        ?>
        <div class="details">
            <div id="map">
                <img id="details-map" src="<?php echo $conf["url"]; ?>Images/details_map.png" width="360" height="380" alt="Map">
            </div>
            <h3 class="details-title">Informations générales</h3>
            <strong>Pseudo</strong> : <?php echo $data->error ? $data->error : ucfirst($data->pseudo_member); ?><br/>
            <strong>Age</strong> : <?php echo $data->Age($data->birth_member); ?> ans<br/>
            <?php
            // For the month of birth
            $mon = $data->Monthdate($data->birth_member);
            $month = $data->month($mon);
            ?>
            <strong>Anniversaire</strong> : Le <?php
            echo $data->Daydate($data->birth_member);
            echo " $month";
            ?><br/>
            <strong>Sexe</strong> : <?php echo $sexe; ?><br/>
            <strong>Ville</strong> : <?php echo $data->city_member; ?><br/>
            <strong>Pays</strong> : <?php echo $data->country_member; ?><br/>
            <?php
            $day2 = $data->Daydate($data->inscription_date_member);
            $mon2 = $data->Monthdate($data->inscription_date_member);
            $month2 = $data->month($mon2);
            $year2 = $data->Yeardate($data->inscription_date_member);
            ?>
            <strong>Date d'inscription</strong> : <?php echo "Le $day2 $month2 $year2" ?><br/>
            <br/>

            <h3 class="details-title">Détails</h3>
            <?php
            if ($data->statut_member == NULL) {
                $data->statut_member = "Non communiquée";
            } else if ($data->statut_member == 1) {
                $data->statut_member = "Célibataire";
            } else if ($data->statut_member == 2) {
                $data->statut_member = "En couple";
            } else if ($data->statut_member == 3) {
                if ($sexe == "Femme") {
                    $data->statut_member = "Mariée";
                } else {
                    $data->statut_member = "Marié";
                }
            }
            ?>
            <strong>Situation</strong> : <?php echo $data->statut_member; ?><br/>
            <?php
            $interest = "Intéréssé par";
            if ($sexe == "Femme") {
                $interest = "Intéressée par";
            }
            if ($data->preference_member == NULL) {
                $preference = "Non communiqué";
            } else if ($data->preference_member == 1) {
                $preference = "Homme";
            } else if ($data->preference_member == 2) {
                $preference = "Femme";
            } else if ($data->preference_member == 3) {
                $preference = "Homme et Femme";
            }
            ?>
            <strong><?php echo $interest; ?></strong> : <?php echo $preference; ?><br/>
            <?php
            if ($data->study_member == 1) {
                $study = "Collège";
            }
            else if ($data->study_member == 2) {
                $study = "Lycée";
            }
            else if ($data->study_member == 3) {
                $study = "BAC + 1";
            }
            else if ($data->study_member == 4) {
                $study = "BAC + 2";
            }
            else if ($data->study_member == 5) {
                $study = "BAC + 3";
            }
            else if ($data->study_member == 6) {
                $study = "BAC + 4";
            }
            else if ($data->study_member == 7) {
                $study = "BAC + 5";
            }
            else if ($data->study_member == 8) {
                $study = " > BAC + 5";
            }
            else if ($data->study_member == 9) {
                $study = "En recherche d'emploi";
            }
            else if ($data->study_member == 10) {
                $study = "Salarié";
            }
            else if ($data->study_member == 11) {
                $study = "Freelance";
            }
            else if ($data->study_member == NULL) {
                $study = "Non communiquée";
            }
            ?>
            <strong>Situation professionnelle</strong> : <?php echo $study; ?><br/>
            
            <br/>

            <h3 class="details-title">A propos de vous</h3>
            <strong>Informations supplémentaires</strong><br>
            <strong>Pseudo skype</strong> : Jean jacques<br>
            <strong>Lien facebook</strong> : xxxxxxxxxxxx
            <hr class="clear"/>
        </div>
        <div class="inside-column-sep"></div>
        <div class="details">
            <strong> Passions</strong><br>

            Tourisme / Sport / <span class="blue">Musique</span> / Cinéma / Cuisine / Xxxxx / Xxxxx / Xxxxx / Xxxxx / Xxxxx
            Xxxxx / Xxxxx / Xxxxx / Xxxxx / Xxxxx.

        </div>
        <br>

        <div class="scroll-content-all">
            <div class="connexion-shadow-1"></div>
            <div class="scroll-pane">
                <div id="scroll-content">

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                    <div class="details-user-box">
                        <a href="#"><img src="<?php echo $conf["url"]; ?>Images/clip-face3.jpg" alt="" width="50"></a>
                        <span>
                            <strong>Stupeflip</strong><br>
                            Album xxxxxxx
                        </span>
                    </div>

                </div>
            </div>
            <div class="connexion-shadow-2"></div>
        </div>

    </div>

</div>
</div> <!-- #inside-column -->
<div id="main-footer">
<?php if (isset($contr)) $contr->loadvWidget("mosaic_pictures"); ?>
</div> <!-- #main-footer -->
</div> <!-- .cfix -->
    <?php if (isset($contr)) $contr->loadvWidget("footer_quotation"); ?>
<div style="display:none;"></div>
