
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/jquery.autocomplete.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>js/popup/style-popup.css" />
<link href="<?php echo $conf["url"]; ?>css/jquery.slider.min.css" rel="stylesheet" />

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>


<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.resize.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery-ui-1.8.8.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.autocomplete.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.text-shadow.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.border.js"></script>

<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/popup/popup.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/jquery.slider.min.js"></script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script src="<?php echo $conf["url"]; ?>js/richmarker.js"></script>
<script type="text/javascript">var lon = "<?php echo $data->coord_member['long_member'];?>"; var lat = "<?php echo $data->coord_member['lati_member'];?>";</script>
<script type="text/javascript">var event_data = <?php echo json_encode($data->event);?>;</script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/evenement/searchEvent.js"></script>

<div class="popup-other popup-othermini" style="display: none; "></div>


<div id="inside-main-max" class="cfix">


    <!-- This is the main content area -->
    <div id="inside-column-max">
        <hr class="top-bar"/>
        <?php //include 'Modules/tchat/notifications.php'; ?>
        <span class="title_event_header"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-fav.png" alt="" class="vam blue-man" width="27" />Rechercher un évènement</span>
        <hr class="clear"/>
        <div class="inside-column-sep"></div>
        <div id="listpassion_searchevent">
            <h2>Passions :</h2>
            <ul>
                <?php
                    foreach($data->passion_category as $val)
                        echo "<li><input checked='checked' type='checkbox' name='passion' id='".$val['id_category']."' value='".$val['id_category']."' /><label for='".$val['id_category']."'>".$val['name_category']."</label></li>";
                ?>
            </ul>
        </div>
        <h2>Recherche à proximité</h2>
        <label>A partir de : </label>
        <select name="from" id="from">
            <option value="here">De chez moi</option>
            <option value="other">Du lieu de mon choix</option>
        </select>
        <div id="changepos">
        </div>
        <br/><br/>
        <label>Distance :</label>
        <span style="display: inline-block; width: 400px; padding: 0 5px;"><input id="distance" type="slider" name="distance" value="25" /></span>
        <hr class="clear" />
        <a href="javascript:void();" onclick="searchEvent()">Rechercher</a>
        <div class="inside-column-sep"></div>
        <div style="height: 800px;" id="map-canvas"></div>
    </div>


</div> <!-- #inside-column -->
<div id="main-footer">
    <div class="connexion-shadow-2 nom"></div>
    <div id="home-icons">
        <img src="<?php echo $conf["url"]; ?>Images/icon-1.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-2.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-3.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-4.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-5.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-6.png" alt="" />
    </div> <!-- #home-icons -->
</div> <!-- #main-footer -->
</div> <!-- .cfix -->

<div class="blue-box-top blue-box-asdf"></div>
<div class="blue-box">
    <div class="blue-box-in cfix equal-heights">
        <div class="blue-box-col ld">
            <div class="equal">
                <p>&laquo;&nbsp;Sam, celui qui conduit, c'est celui qui ne bois pas.&nbsp;&raquo;</p>
                <p class="ra"><strong><em class="grey">Mister Cocktail</em></strong></p>
            </div> <!-- .equal -->
        </div> <!-- .blue-box-col -->
        <div class="blue-box-col rd">
            <div class="equal">
                <p>&laquo;&nbsp;Ne soyez pas timide, les autres ne vont pas vous manger.&nbsp;&raquo;</p>
                <p class="ra"><strong><em class="grey">Mister Cocktail</em></strong></p>
            </div> <!-- .equal -->
        </div> <!-- .blue-box-col -->
    </div> <!-- .blue-box-in -->
</div> <!-- .blue-box -->

