
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/jquery.listederoulante.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>css/jquery.autocomplete.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $conf["url"]; ?>js/popup/style-popup.css" />

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>


<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.resize.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery-ui-1.8.8.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.autocomplete.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.text-shadow.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.border.js"></script>

<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.listederoulante.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/popup/popup.js"></script>

<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.resize.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery-ui-1.8.8.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.border.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jquery.upload.js"></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/popup/popup.js"></script>
<script type="text/javascript">var searchevent_dep = <?php echo json_encode($data->departments); ?></script>
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/evenement/searchEvent.js"></script>
<link href="/maps/documentation/javascript/examples/default.css" rel="stylesheet">
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
    function handleNoGeolocation(errorFlag) {
        if (errorFlag) {
            var content = 'Error: The Geolocation service failed.';
        } else {
            var content = 'Error: Your browser doesn\'t support geolocation.';
        }

        var options = {
            map: map,
            position: new google.maps.LatLng(60, 105),
            content: content
        };

        var infowindow = new google.maps.InfoWindow(options);
        map.setCenter(options.position);
    }

    function initialize() {
        var myLatlng = new google.maps.LatLng(-25.363882, 131.044922);
        var mapOptions = {
            zoom: 4,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var pos = new google.maps.LatLng(position.coords.latitude,
                        position.coords.longitude);

                var infowindow = new google.maps.InfoWindow({
                    map: map,
                    position: pos,
                    content: 'Location found using HTML5.'
                });

                map.setCenter(pos);
            }, function() {
                handleNoGeolocation(true);
            });
        } else {
            // Browser doesn't support Geolocation
            handleNoGeolocation(false);
        }

        var contentString = 'ii';

        var infowindow = new google.maps.InfoWindow({
            content: contentString,
            maxWidth: 200
        });

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title: 'Uluru (Ayers Rock)'
        });
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.open(map, marker);
        });
    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>
<div class="popup-other popup-othermini" style="display: none; "></div>


<div id="inside-main-max" class="cfix">


    <!-- This is the main content area -->
    <div id="inside-column-max">
        <hr class="top-bar"/>
        <?php //include 'Modules/tchat/notifications.php'; ?>
        <span class="title_event_header"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-fav.png" alt="" class="vam blue-man" width="27" />Rechercher un évènement</span>
        <hr class="clear"/>
        <div class="inside-column-sep"></div>
        <br/><br/><br/><br/>
        <div class="inside-column-sep"></div>
        <div style="height: 500px;" id="map-canvas"></div>
    </div>


</div> <!-- #inside-column -->
<div id="main-footer">
    <div class="connexion-shadow-2 nom"></div>
    <div id="home-icons">
        <img src="<?php echo $conf["url"]; ?>Images/icon-1.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-2.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-3.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-4.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-5.png" alt="" />
        <img src="<?php echo $conf["url"]; ?>Images/icon-6.png" alt="" />
    </div> <!-- #home-icons -->
</div> <!-- #main-footer -->
</div> <!-- .cfix -->

<div class="blue-box-top blue-box-asdf"></div>
<div class="blue-box">
    <div class="blue-box-in cfix equal-heights">
        <div class="blue-box-col ld">
            <div class="equal">
                <p>&laquo;&nbsp;Sam, celui qui conduit, c'est celui qui ne bois pas.&nbsp;&raquo;</p>
                <p class="ra"><strong><em class="grey">Mister Cocktail</em></strong></p>
            </div> <!-- .equal -->
        </div> <!-- .blue-box-col -->
        <div class="blue-box-col rd">
            <div class="equal">
                <p>&laquo;&nbsp;Ne soyez pas timide, les autres ne vont pas vous manger.&nbsp;&raquo;</p>
                <p class="ra"><strong><em class="grey">Mister Cocktail</em></strong></p>
            </div> <!-- .equal -->
        </div> <!-- .blue-box-col -->
    </div> <!-- .blue-box-in -->
</div> <!-- .blue-box -->

