<?php
if ($data->id_member != $_SESSION['id_member']) {
    $own = false;
    $ownbool = 0;
} else {
    $own = true;
    $ownbool = 1;
    $data->id_member = $_SESSION['id_member'];
}

if ($own == true) {
    ?>
    <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jeditable.js"></script>
    <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/profil/modify-profil.js"></script>
    <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/jeditable-masked.js"></script>
    <script type="text/javascript" src="<?php echo $conf["url"]; ?>js/files/maskedinput.js"></script>
    <?php
}
?>

<div class="popup-other popup-othermini" style="display: none; "></div>
<!-- the jScroll script -->
<script type="text/javascript" src="<?php echo $conf["url"]; ?>js/scroll.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.scroll-pane').jScrollPane({
            verticalDragMaxHeight: 42
        });

    });
</script>

<script type="text/javascript">
    $(document).ready(function() {
        $('.scroll-pane').jScrollPane({
            verticalDragMaxHeight: 42
        });

    });
</script>
<div id="inside-main" class="cfix">
    <div id="sidebar-left">
        <div id="sidebar-left-in">
            <?php
            //include 'Modules/amis/listeamis.php';
            ?>
            <?php
            /*             * ************************************************* TCHAT *************************************** */
            //include 'Modules/tchat/tchat-left.php';
            /*             * ************************************************* FINTCHAT *************************************** */
            ?>
            <?php if (isset($contr)) $contr->loadvWidget("friends_online"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("statistics"); ?>
        </div> <!-- #sidebar-left-in -->
    </div> <!-- #sidebar-left -->

    <div id="sidebar-right">
        <div id="sidebar-right-in">
            <?php if (isset($contr)) $contr->loadvWidget("events_my"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("events_sugest"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("sponsoring"); ?>
        </div> <!-- #sidebar-right-in -->
    </div> <!-- #sidebar-right -->

    <!-- This is the main content area -->
    <div id="inside-column">
        <?php
        $datasent['own'] = $ownbool;
        $datasent['id_member'] = $data->id_member;
        if (isset($contr))
            $contr->loadvWidget("profilNavigation", "profilNavigation", $datasent);
        ?>

        <div class="details">
        </div>

    </div>
</div> <!-- #inside-column -->
<div id="main-footer">
<?php if (isset($contr)) $contr->loadvWidget("mosaic_pictures"); ?>
</div> <!-- #main-footer -->
</div> <!-- .cfix -->
<?php if (isset($contr)) $contr->loadvWidget("footer_quotation"); ?>
<div style="display:none;"></div>
