<?php if (isset($contr)) $contr->loadvWidget("profil_js_include"); ?>

<div class="popup-other popup-othermini" style="display: none; "></div>


<div id="inside-main" class="cfix">
    <div id="sidebar-left">
        <div id="sidebar-left-in">
            <?php
            //include 'Modules/amis/listeamis.php';
            ?>
            <?php
            /*             * ************************************************* TCHAT *************************************** */
            //include 'Modules/tchat/tchat-left.php';
            /*             * ************************************************* FINTCHAT *************************************** */
            ?>
            <?php if (isset($contr)) $contr->loadvWidget("statistics"); ?>
        </div> <!-- #sidebar-left-in -->
    </div> <!-- #sidebar-left -->

    <div id="sidebar-right">
        <div id="sidebar-right-in">
            <?php if (isset($contr)) $contr->loadvWidget("events_my"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("events_sugest"); ?>
            <?php if (isset($contr)) $contr->loadvWidget("sponsoring"); ?>
        </div> <!-- #sidebar-right-in -->
    </div> <!-- #sidebar-right -->

    <!-- This is the main content area -->
    <div id="inside-column">
        <hr class="top-bar"/>
        <?php //include 'Modules/tchat/notifications.php'; ?>
        <span class="title_event_header"><img src="<?php echo $conf["url"]; ?>Images/menu-icon-fav.png" alt="" class="vam blue-man" width="27" />Mon profil</span>
        <hr class="clear"/>
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div class="cfix">
                <div class="conversation-main">
                    <div class="conversation-main-inside cfix">
                        <div class="ld user-titlro">
                            <strong><em><?php echo ucfirst($data->profile_pseudo); ?></em></strong>
                            <br /><br />
                            <strong><em><a href="#" class="rev blue">Resume</a></em></strong>
                        </div> <!-- .user-titlro -->
                        <ul class="user-iconies cfix">
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-resume.png" alt="" /></span>
                                    <span class="user-iconies-2">Resume</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-photos.png" alt="" /></span>
                                    <span class="user-iconies-2">Photos</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-passions.png" alt="" /></span>
                                    <span class="user-iconies-2">Passions</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-contact.png" alt="" /></span>
                                    <span class="user-iconies-2">Contact</span>
                                </a></li>
                            <li><a href="#">
                                    <span class="user-iconies-1"><img src="<?php echo $conf["url"]; ?>Images/icon-parameter.png" alt="" /></span>
                                    <span class="user-iconies-2">Parametres</span>
                                </a></li>
                        </ul> <!-- .user-iconies -->
                    </div> <!-- .conversation-main-inside -->
                </div>
                <div class="conversation-left">
                    <a href="#" class="user-avatar bgr-blue"><img src="/<?php echo $data->profile_maphoto; ?>" alt="" width="42" /></a>
                    <a href="javascript:void()" id="modifAvatar">Modifier ma photo</a>
                </div> <!-- .conversation-left -->
            </div> <!-- .cfix -->
        </div>
        <div class="inside-column-sep"></div>
        <div class="inside-column-inside">
            <div id="contentprofil">
                <?php
                if (empty($data->error['profil'])) {
                    ?>

                    <h2 class="title_underline">Ajouter des Passions</h2>
                    <input class="contentinput ac_input" type="text" name="passionvalue" id="passionvalue" value="Saisissez le nom d&#39;une de vos passions" autocomplete="off">
                    <input type="hidden" name="categorievalue" id="categorievalue" value="">
                    <a href="javascript:void();" id="contentvalid" class="contentvalid">Ajouter à mes passions</a><br /><br />
                    <hr class="clear"/>
                    <h2 class="title_underline">Passions</h2>

                    <?php
                    if (count($data->profile_passion) == 0)
                        echo "<div id='content_passion'>Aucune passion liée pour le moment</div>";
                    else {
                        echo "<div id='content_passion'>";
                        foreach ($data->profile_passion as $key => $t_categorie_passion) {
                            echo "<h3 class='title_underline'>" . ucfirst($data->profile_passioncat[$key]) . "</h3><ul class='listepassions cat" . $key . "'>";
                            foreach ($t_categorie_passion as $t_passion) {
                                echo "<li id='passion" . $t_passion['id_passion'] . "'><img src='/" . ($t_passion['icone'] != "" ? $t_passion['icone'] : $t_passion['icone_cat']) . "' alt='" . $t_passion['name_passion'] . "' />" . ucfirst($t_passion['name_passion']) . "<br/><a href='javascript:void()' onclick='delete_passion(" . $t_passion['id_passion'] . ")'>Supprimer</a></li>";
                            }
                            echo "</ul>";
                        }
                        echo "</div>";
                    }
                    ?>
                </div>

                <?php
            } else {
                echo $data->error['profil'];
            }
            ?>
        </div>
    </div>


</div> <!-- #inside-column -->
<div id="main-footer">
    <div class="connexion-shadow-2 nom"></div>
    <?php if (isset($contr)) $contr->loadvWidget("mosaic_pictures"); ?>
</div> <!-- #main-footer -->
</div> <!-- .cfix -->

<?php if (isset($contr)) $contr->loadvWidget("footer_quotation"); ?>
